---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by reebdeve.
--- DateTime: 2022/7/11 20:02
---
found  = false
N = 8 -- size of chessboard
function isplaceok(a,n,c)
    for i = 1,n-1 do
        if(a[i] == c) or (a[i]-i == c-n) or (a[i] + i == c + n) then
            return false
        end
    end
    return true
end

-- print the chessboard
function printsolution(a)
    for i = 1,N do
        for j = 1,N do
            io.write(a[i] == j and "X" or "-"," ")
        end
        io.write("\n")
    end
    io.write("\n")
end

-- put all the queens from n to N on the chessboard
function addqueen(a,n)
    if n > N and found==false then
        printsolution(a)
        found=true
    else --try to place the nst queens
        for c = 1,N do
            if isplaceok(a,n,c)then
                a[n] = c
                addqueen(a,n+1)
            end
        end
    end
end

addqueen({},1)