---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by reebdeve.
--- DateTime: 2022/7/17 15:16
---

--- 没有format，使用默认都转换规则
io.write("sin(3) = ",math.sin(3),"\n")
--- 使用string format 来格式化数据
io.write(string.format("sin(3) = %4f\n",math.sin(3)))

--- io.read
t = "hello world,i am a bad boy"
t = string.gsub(t,"bad","good")
print(t)

local lines = {}

---
--print(io.open("non-existent-file","r"))
--local f = assert(io.open("non-existence file","r"))
---
--- print(io.open("/etc/passwd","w"))

---
local file_open = io.open("./test7.txt","r")
-- file_open:write("stupid test ")
local readcontent = file_open:read("a")
print(readcontent)

io.stderr:write("you are stupid")

---  在不改变当前位置的情况下获取文件大小
function fsize(file)
    local current = file:seek() -- 保存当前位置
    local size = file:seek("end") --获取文件大小
    file:seek("set",current)    -- 恢复当前位置
    return size
end

print("\n",os.getenv("HOME"))

function createDir (dirname)
    os.execute("mkdir"..dirname)
end


