---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by reebdeve.
--- DateTime: 2022/7/11 19:47
---

function test(n)
    if n < 0 then
        print("you are stupid")
        return -1
    end
    if n==0 then
        return 1
    else
        return n*test(n-1)
    end
end

a = io.read("*n")
print(test(a))