---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by reebdeve.
--- DateTime: 2022/7/13 15:25
---

--- 练习一

print("--------------method one-------------")
page = [=[
    <![CDTA[
        hello world
    ]]>
]=]
io.write(page)

print("--------------method two-------------")

local s = "<![CDTA[\n    hello world \n ]]>"

print(s)


---  练习二
local s2 = '\n \a \b \f \n \r \t \v \\ \" \' '

---  练习三

function insert(str1,pos,str2)
    return string.sub(str1,1,pos-1)..str2..string.sub(str1,pos)
end

print(insert("hello world",7,"small "))
print(insert("hello world",1,"start: "))


--- 练习四

--- 练习五

function remove(str,pos,len)
    local len_s = string.len(str)
    if pos + len >= len_s then
        -- pos后数据全部丢掉
        if pos <= 1 then
            return nil
        else
            return string.sub(str,1,pos-1)
        end
    else
        if pos <= 1 then
            return string.sub(str,pos+len+1)
        else
            return string.sub(str,1,pos-1)..string.sub(str,pos+len+1)
        end
    end
end
print("------------------exp 4.5------------")
print(remove("hello world",2,5))

--- 练习六
--- 练习七
print("-------------------exp 7--------------")
function ispali(str)
    local len_s = string.len(str)
    local mid = len_s / 2
    for i = 1,mid,1 do
        j = len_s - i + 1
        if string.sub(str,i,i) ~= string.sub(str,j,j) then
            return false
        end
    end
    return true
end

print(ispali("step on no pets"))
print(ispali("hello world"))
