---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by reebdeve.
--- DateTime: 2022/7/12 16:42
---

page = [[
    <html>
    <head>
        <title> An HTML Page </title>
]]

io.write(page)


data = "\x00\x01\x02\z
        \x03\x04\x34 "
print("data is"..data)

print(10 .. 20)

print("10" + 1)

print(string.rep("abc",2))
print(string.reverse("this is dog"))
print(string.lower("a long line"))
print(string.upper(" a long line"))

print("-------------------")
s = "[in brackets]"

print(string.sub(s,1,2))
print(string.sub(s,1,-1))
print(string.sub(s,-1,-1))

print("-------------------")
print(string.char(97))
print(string.byte("abc"))
print(string.byte("abc",2))
print(string.byte("abc",-1))
print(string.byte("abc",1,2))

print("---------------------")
print(string.format("x = %d y = %d",10,20))
print(string.format("x = %x",200))
print(string.format("x = 0x%X",200))
print(string.format("x = %f",2000))

tag , title = "h1","a title"
print(string.format("<%s>%s</%s>",tag,title,tag))


print(string.format("pi = %.4f",math.pi))

d = 5;m = 11;y = 1990;

print(string.format("%02d/%02d/%04d",d,m,y))


print(string.find("hello world","wor"))
print(string.find("hello world","war"))

