---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by reebdeve.
--- DateTime: 2022/7/16 22:01
---

--- exp1
--- 6.1 编写一个函数，该函数的参数为一个数组，打印出该数组的所有元素。
function printAllValues(a)
    if type(a) ~= "table" then
        return false
    end
    for i = 1,#a do
        print(a[i])
    end
end

print(printAllValues({1,2,3,4,5,6,7,8}))


--- exp2
--- 6.2 编写一个函数，该函数的参数可变数量的一组值，返回值为除第一个元素之外的其他所有值

function returnVal(first,...)
    return ...
end

--- test
print(returnVal(1,2,3,4,5))
--- exp3
--- 6.3 请编写一个函数，该函数的参数可变数量的一组值，返回除最后元素之外的所有值
function removeLastVal(...)
    local t = table.pack(...)
    table.remove(t)
    return table.unpack(t)
end
--- test
print(removeLastVal(1,2,3,4,5))

--- exp4
--- 6.4 请编写一个函数，该函数用于打乱一个指定的数组。请保证所有的排列都是等概率的。

function shuffle(array)
    math.randomseed(os.time())
    for i = #array,2,-1 do
        local j = math.random(1,i)
        if i ~= j then
            local temp = array[i]
            array[i] = array[j]
            array[j] = temp
        end
    end
end

--- test
local a = {1,2,3,4,5,6,7,8}
shuffle(a)
printAllValues(a)

--- exp5
--- 6.5 编写一个函数，它传入一个数组并打印该数组中所有元素的组合。
--- 可以使用组合的递推公式C(n,m) = C(n-1,m-1) + C(n-1,m)
--- 当n < m 时，组合不存在； 当m = 0时， 只有一种组合（一个元素都没有）
local isContain = {}
local function Combination(a,index)

end




