---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by reebdeve.
--- DateTime: 2022/7/19 18:21
---

--- exp1
--- 8.1

--- exp2
--- 8.2
--- 描述Lua语言中实现无条件循环的四种方式
while true do
    print("loop1")
end

for i = 1,math.huge do
    print("loop2")
end

::loop::
print("loop3")
goto loop

repeat
    print("loop4")
until false

