---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by reebdeve.
--- DateTime: 2022/7/17 23:44
---

x = 10
local i = 1 -- 局部代码段

while i <=  x do
    local x = i * 2
    print(x)
    i = i + 1
end

--- 条件控制语句
MAXLINES = 10

if a < 0 then a = 0 end

if a < b then return a else return b end

if line > MAXLINES then line = 0 end

if op == "+" then
    r = a + b
elseif op == '-' then
    r = a - b
elseif op == "/" then
    r = a / b
else
    error("invalid operation")
end

--- while
local i = 1
while a[i] do
    print(a[i])
    i = i + 1
end

--- 输出第一个非空的行
local line
repeat
    line = io.read()
until line ~= ""
print(line)


--- break return goto
local i = 1
while a[i] do
    if a[i] == v then
        return i
    end
    i = i + 1
end

