---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by reebdeve.
--- DateTime: 2022/7/13 16:09
---

a = {}
k = "x"
a[k] = 10
a[20] = "great"
print(a["x"])
print(a[20])

print(string.rep("-",30))

a = {}
x = "y"
a[x] = 10


i = 10; j = "10"; k = "+10"

a = {}
a[i] = "number key"
a[j] = "string key"
a[k] = "another string key"

print(a[i])
print(a[j])
print(a[k])

print(a[tonumber(j)])
print(a[tonumber(k)])



print(string.rep("-",20))

days = {"7","1","2","3","4","5","6"}
print(days[4])

a = {x = 10, y = 20}

w = {x = 0, y = 0, label = "console"}

x = {math.sin(0),math.sin(1),math.sin(2)}

w[1] = "another word"

print(w[1])

x.f = w

print(w[x])
print(w["x"])
print(x.f)
print(x.f[1])
w.x = nil
print(w.x)
print(w[x])


print(string.rep("-",50))

polyline = {
    color = "blue",
    thickness = 2,
    npoints =  4,
    {x = 0,  y = 0}, -- polyline[1]
    {x = 1,  y = 1}, -- polyline[2]
    {x = 2,  y = 2}, -- polyline[3]
    {x = 3,  y = 3}, -- polyline[4]
}

print(polyline[2].x)
print(polyline[3].x)


opnames = {["+"] = "add",["-"] = "sub",
           ["*"] = "mul",["/"] = "div"}

i = 20; s = "-"
a = {[i+0] = s,[i+1] = s..s,[i+2] = s..s..s}

print(opnames[s])
print(a[22])
print(string.rep("-",50))

print(string.rep("-",20))

t = {10,print,12,"hi"}

for k,v in ipairs(t) do
    print(k,v)
end


print(string.rep("-",100))

t = {10,print,12,"hi"}

for k = 1, #t do
    print(k,t[k])
end


print(string.rep("-",50))

a = {"a","b","c","d"}
table.move(a,1,#a,2)
a[1] = "e"
for k,v in ipairs(a) do
    print(k,v)
end





