---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by reebdeve.
--- DateTime: 2022/7/11 18:04
---

function norm(x,y)
    return math.sqrt(x^2+y^2)
end

function twice(x)
    return 2*x
end

