---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by reebdeve.
--- DateTime: 2022/7/11 17:51
---

-- define a n! function
function fact(n)
    if n == 0 then
        return 1
    else
        return n * fact(n-1)
    end
end

print("enter  a number")
a  = io.read("*n") -- read a  number
print(fact(a))